version: '3.1'
services:
  carousel:
    container_name: carousel
    build:
      context: ../
    ports:
      - 8082:8082
    environment:
      - MQTT_URL=ws://172.30.22.35:8885
    depends_on:
      - mqtt

  mqtt:
    hostname: mqtt
    image: eclipse-mosquitto
    restart: always
    ports:
      - 8885:8885
    volumes:
     - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
